server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://115.159.118.77:3306/OnlineExams?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: sast
    password: sast_forever

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml

logging:
#  file:
#    name: ./log/materialized.log
#    path: ./log/
#  logback:
#    rollingpolicy:
#      max-file-size: 256MB
#      max-history: 20
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger- %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: info
